version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: frontify
      MARIADB_DATABASE: colors
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql

  backend:
    image: color-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=database:3306
      - DB_USERNAME=root
      - DB_PASSWORD=frontify
    links:
      - "db:database"